dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "6"

install:
  - npm install -g @angular/cli
  - npm install

before_script:
  - 'export CHROME_BIN=chromium-browser'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ng -v

script:
  - ng lint
  - ng test --no-watch --code-coverage
  - ng e2e
  - ng build --prod

after_success:
  - npm run coveralls

