export const environment = {
  production: false,
  default_language: 'fr',
  url_base_api: 'https://h7alt5p1bi.execute-api.ca-central-1.amazonaws.com/dev/',
  token_paysafe: 'T1QtMjM1MjAwOkItcWEyLTAtNWI4NDE0ZDYtMS0zMDJjMDIxNDEzMzhmMzEzN2FmZTgxNmUxMmE4YWJmYTk1NTVkN2VlZWQ5ZWU5ZjgwMjE0M2E1NzE5NDZjYzg3ODgwN2ZkZDU0NjkyODA1ZTg3ZjI5MjQ0ZGRiNg==',
  paths_api: {
    activation: '/users/activate',
    authentication: '/authentication',
    users: '/users',
    organizations: '/organizations',
    domains: '/domains',
    academic_fields: '/academic_fields',
    academic_levels: '/academic_levels',
    reset_password: '/reset_password',
    change_password: '/change_password',
    activate_user: '/users/activate',
    workplaces: '/workplaces',
    profile: '/profile',
    time_slots: '/time_slots',
    periods: '/periods',
    memberships: '/memberships',
    reservationPackages: '/packages',
    pictures: '/pictures',
    cards: '/credit_cards',
    orders: '/orders',
  }
};
